/**
 * ID type system to prevent UUID confusion.
 *
 * ARCHITECTURE DECISION:
 * - Backend is the SOLE authority for server IDs
 * - Frontend NEVER generates UUIDs for server entities
 * - New entities use null until server responds
 * - No optimistic local IDs (simpler, prevents bugs)
 */

import { UiBoundingBox } from './coordinates';

/**
 * Server-generated entity ID (UUID from backend)
 * Never generated by frontend
 */
export type ServerId = string;

/**
 * Person entity with server ID
 */
export interface Person {
  id: ServerId;
  name: string;
  collection_id: ServerId;
}

/**
 * Face tag for a photo
 * person_id is null for unknown/untagged faces
 */
export interface FaceTag {
  person_id: ServerId | null;
  bbox: UiBoundingBox; // Uses UI coordinate type
}

/**
 * Check if a value is a valid non-null server ID
 */
export function isValidServerId(id: unknown): id is ServerId {
  return typeof id === 'string' && id.length > 0;
}

/**
 * Validate server ID or throw
 */
export function requireServerId(id: unknown, context: string): ServerId {
  if (!isValidServerId(id)) {
    throw new Error(`Invalid server ID in ${context}: ${id}`);
  }
  return id;
}
